# image will be published to ghcr.io/<user>/<name>
name: chillpert-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos: 
      - https://cli.github.com/packages/rpm/gh-cli.repo
    install:
      - gnome-shell-extension-auto-move-windows
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-appindicator
      - git
      - git-lfs
      - gh
    remove:
      - firefox
      - firefox-langpacks
      - gnome-tour
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.mozilla.firefox
        - org.gimp.GIMP
        - io.mpv.Mpv
        - com.discordapp.Discord
        - com.mattjakeman.ExtensionManager
        - com.obsproject.Studio
        - com.protonvpn.www
        - com.spotify.Client
        - com.teamspeak.TeamSpeak
        - com.valvesoftware.Steam
        - im.riot.Riot
        - io.exodus.Exodus
        - io.freetubeapp.FreeTube
        - io.github.achetagames.epic_asset_manager
        - io.github.trigg.discover_overlay
        - me.kozec.syncthingtk
        - net.ankiweb.Anki
        - com.github.tchx84.Flatseal
        - org.flameshot.Flameshot
        - org.keepassxc.KeePassXC
        - org.libreoffice.LibreOffice
        - org.mozilla.Thunderbird
        - org.signal.Signal
        - org.gnome.Loupe
        - org.gnome.Evince
        - org.gnome.Calculator
        - org.gnome.Characters
        - org.gnome.baobab
        - org.gnome.Music
        - org.gnome.NautilusPreviewer
      remove:
        - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - DejaVuSansMono

  - type: bling
    install:
      - dconf-update-service
